### ISSUE TITLE
Build support for Shared Projects

### ISSUE THREAD

**Issue by ClassicThunder** [hach-que/Protobuild#113]
Is there any intention of adding the ability to generate shared projects?

I think there would be only  2 files that need to be generated.

A .projitems [example](https://github.com/ClassicThunder/MonoGame-EventDriven-Input/blob/master/EventDriven_Input.projitems) that keeps track of the files and folders. 
A .shproj [example](https://github.com/ClassicThunder/MonoGame-EventDriven-Input/blob/master/EventDriven_Input.shproj) that references the projitems and keeps track of the extensions needed.

[Info about shared projects](http://www.c-sharpcorner.com/UploadFile/7ca517/shared-project-an-impressive-features-of-visual-studio-201/)

**Comment by hach-que** [comment]
I'm guessing this suggestion is to use them to contain platform specific code?

For us to use shared projects, we'd need to generate a shared project for every combination of projects, so not only would we need a Linux and Windows shared project for every real project, we'd also need a "Windows+Linux" project as well, and we'd need to do that for every platform combination. This means generating factorial N shared projects for every actual project in the solution, where N is the number of platforms. Obviously that's not a solution that will scale. 

If that's not the suggestion, you can already do this for non-code content with a content project.

**Comment by ClassicThunder** [comment]
Hmm I really didn't think this through. I'm in the fairly unique situation where we have made a project that is build on top of an API has been re-implemented multiple times, so one shared project works with all of the re-implementations. I was basically hoping to leverage protobuild to prevent manual maintenance of the shproj.

**Comment by hach-que** [comment]
Why doesn't a normal assembly reference work in that case?

**Comment by hach-que** [comment]
I'm planning on supporting an equivalent to shared project functionality in Protobuild so that libraries can inject template classes into executables that use them. 

The use case for my scenario is to allow Protogame to provide an implementation of the main program entry point for various platforms to simplify application startup, however it should work for your use case as well.

**Comment by hach-que** [comment]
Documentation on using include projects is now online at https://protobuild.readthedocs.org/en/latest/include_projects.html.
