### ISSUE TITLE
Intention of Transition: Default framework for desktop and mobile platforms to change to .NET 4.5, default C# language version to change to 6.0

### ISSUE THREAD

**Issue by hach-que** [hach-que/Protobuild#119]
### What is an intention of transition?

When developing Protobuild, we strive to ensure that changes are forward compatible and don't break existing uses.  However, sometimes we need to change the default behaviour of Protobuild, either because of changing circumstances, new features or because the existing default behaviour is incorrect or faulty.

An intention of transition indicates that a default will be changing in a future of Protobuild, and outlines the reason for the change.

### What is changing?

With Mono shipping only 4.5 assemblies, and with .NET Core still not stable enough for production use, it is clear that we need to change the default target framework for desktop and mobile platforms in Protobuild.  The intention is to change the default framework to .NET 4.5 and it's mobile equivalents.

With the official Mono release now shipping only 4.5 assemblies, we can no longer remain both backward compatible with Linux distros that ship broken versions of Mono, and Linux distros which ship new correctly working versions of Mono.  In this case we've decided to favour the newer Linux distros which ship working versions of Mono, over those that still ship broken versions.  Since Xamarin is now providing official repositories with the latest version of Mono for most distributions, our recommendation is that you point your users to install the official Xamarin version of Mono where possible.  For those users running Linux, they can install Mono from http://www.mono-project.com/download/#download-lin.

We expect that Mono works fully on Mac (this is what Xamarin runs on), and that the latest language features correctly on mobile devices (this is what Xamarin officially supports).  .NET 4.5 is stable on Windows and is known to work well.

In addition, we will be changing the language version to C# 6.0 by default.

### When is the change occurring?

This change will on the 17th of October 2015.  Versions of Protobuild downloaded after this date on the master branch will default to .NET 4.5.

In the future when .NET Core reaches platform stability, we still intend on changing the default to .NET Core for desktop platforms.  See #87 for the state of that change.

### What is affected?

This will change the default .NET framework for the Windows, MacOS, Linux, Android and iOS platforms.  No other platforms are affected (including variants of the Windows platform).

### What do I need to do to keep the existing behaviour?

The behaviour will only change when you start using a version of `Protobuild.exe` that includes the new behaviour.  If you keep your existing version of Protobuild, the behaviour will not change.

If you are intending to use a version of `Protobuild.exe` after the change is made, you can keep the existing behaviour by explicitly specifying the .NET framework for a platform through the `<FrameworkVersions>` option, detailed at http://protobuild.readthedocs.org/en/latest/project_properties.html#frameworkversions.  In particular, you'll need to add the following section to the `<Properties>` section of all projects that you want to keep on .NET 4.0:

```
<Properties>
  <!-- ... -->
  <FrameworkVersions>
    <Platform Name="Windows">
      <Version>v4.0</Version>
    </Platform>
    <Platform Name="MacOS">
      <Version>v4.0</Version>
    </Platform>
    <Platform Name="Linux">
      <Version>v4.0</Version>
    </Platform>
    <Platform Name="Android">
      <Version>v4.2</Version>
    </Platform>
  </FrameworkVersions>
  <LangVersion>4</LangVersion>
  <!-- ... -->
</Properties>
```

**Comment by hach-que** [comment]
@tomspilman This change will impact MonoGame if Protobuild is upgraded to a build after October 18th.

**Comment by tomspilman** [comment]
I'm swamped with work... don't have the time to ponder the implications of this.  Worst case we use an old revision Protobuild if we find we have some problem with the change...  but I suspect it will be fine.

**Comment by hach-que** [comment]
A preview of this change is now available at https://github.com/hach-que/Protobuild/tree/dotnet-45.

This will change built applications to use the 14.0 build tools (Visual Studio 2015), .NET 4.5 as the framework and C# 6 as the default language.

**Comment by hach-que** [comment]
I'm pushing this change out now.  The previous version of Protobuild before this change is https://github.com/hach-que/Protobuild/blob/7a86b400c3b198520281152b80819d83d5f48d32/Protobuild.exe.
