### ISSUE TITLE
Handle Windows SDK version numbers

### ISSUE THREAD

**Issue by hach-que** [hach-que/Protobuild#147]
See https://github.com/mono/MonoGame/issues/4367#issuecomment-168305952.

**Comment by BrianPeek** [comment]
You can likely determine either from:

a) Registry: HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0\ProductVersion

and/or

b) Parse C:\Program Files (x86)\Windows Kits\10\SDKManifest.xml

Please do not take either suggestion as official guidance or information. :)

**Comment by hach-que** [comment]
Ah okay, so there's only one SDK installed at a time?

I have `10.0.10240` set as the `ProductVersion`.  If I install a later SDK, does that value get overridden?

**Comment by BrianPeek** [comment]
Yes, if you install the 10586 SDK, you should see the value as 10.0.10586 in each location.

**Comment by hach-que** [comment]
This is now fixed as of 6dfc542.
