### ISSUE TITLE
Project Language 

### ISSUE THREAD

**Issue by tomspilman** [hach-que/Protobuild#150]
I'm trying to do the following:

```
<?xml version="1.0" encoding="utf-8" ?>
<ExternalProject Name="SomeExternals">  
  <Platform Type="MyPlatform">    
    <Project  Name="cppProjectName" 
              Language="C++"              
              Guid="1DBEF0FF-4EF7-4B4A-AF94-32A0CCB25547"
              Path="cppProjectName.vcxproj">
    </Project>
  </Platform>
</ExternalProject>
```

Which should add the `cppProjectName` C++ project into the solution.  It does it add it to the solution, but it sets the wrong GUID making the C++ project look like a C# project.

It seems like the `GenerateSolution.xslt` is handling this:

https://github.com/hach-que/Protobuild/blob/master/Protobuild.Internal/BuildResources/GenerateSolution.xslt#L131

But for some reason the `language` parameter is blank for this project.

It seems to me like maybe the processing in `SelectSolution.xslt ` : 

https://github.com/hach-que/Protobuild/blob/b5ec1312e2a8fca0c95fc7a3dbc5b74f6e0631d8/Protobuild.Internal/BuildResources/SelectSolution.xslt#L94

Isn't passing thru the language value.

Does this make sense @hach-que ?

**Comment by tomspilman** [comment]
Also for some reason `-extract-xslt` doesn't seem to output the `SelectSolution.xslt`.  Is that by design or an omission?

**Comment by hach-que** [comment]
Ah I didn't expect people to try and include external C++ projects. While
that should be supported, at the moment the intention is to have a normal
project which you put the Language tag on (see the functional tests for C++
projects as an example).

Select solution should be being output, if it is not then that is a bug.

**Comment by tomspilman** [comment]
> Select solution should be being output, if it is not then that is a bug.

Yeah... it is a bug then as it isn't being extracted.

**Comment by hach-que** [comment]
> In my case I have native code for console in an external C++ project that I want to be built as part of the solution. This worked with my old customized xslt setup... trying to do the same now with stock Protobuild.

While I'll work on C++ external projects now, is there anything blocking you from using a standard project with the `Language="C++"` attribute for that project?

**Comment by hach-que** [comment]
(I fixed the SelectSolution bug by the way)

**Comment by hach-que** [comment]
You could also declare a custom C++ XSLT for a normal C++ project as well by creating a "GenerateProject.VisualStudio.<Platform>.xslt" file.

**Comment by hach-que** [comment]
This is now implemented in fac545b.

**Comment by tomspilman** [comment]
> is there anything blocking you from using a standard project with the  Language="C++"  attribute for that project?

I don't know if I understand what you specifically mean by "standard project".  However if you mean define all the source files and let Protobuild generate the C++ project for me...  no I won't do that.

I see Protobuild as only beneficial if you have lots of target platforms, several host platforms, or different IDEs to support.  This C++ project is for only one target platform, only works on one host platform, and only works in VS.  There is no benefit of any kind to using Protobuild for this project...  it would only serve to make things more complex.

I also have a few C# projects I reference as externals like this for the same reason.  Only one host, target, and IDE to consider.  Making these Protobuild projects is just a waste of time for me.

> (I fixed the SelectSolution bug by the way)

Great... will be much easier to debug issues with that easily extracted again.

> This is now implemented in  fac545b .

Thanks!  I'll report back if I have any more issues with that, but I suspect all is well now.

**Comment by hach-que** [comment]
The advantages of letting Protobuild generate the C++ and C# projects (even when they don't contain platform-specific code) are:

- You don't get any of the machine-specific cruft that Visual Studio likes to put in project files, so there aren't unnecessary changes in your Git repo to those files.
- When Protobuild generates the C++ projects, it knows how to configure the C# project to reference them properly.
- This doesn't apply to you, but when you use <Prohect

**Comment by hach-que** [comment]
Ugh, Github on mobile :/

**Comment by tomspilman** [comment]
Yeah... None of those are really any issues in our case.  But we will keep it in mind for other cases.

**Comment by tomspilman** [comment]
FYI.  This fix worked great.  Thanks again!
