### ISSUE TITLE
Feature: Add override for the visual studio solution file format

### ISSUE THREAD

**Issue by totallyeviljake** [hach-que/Protobuild#34]
The solution file format is hard coded in the GenerateSolution.xslt. There should be an override for this in the Platform tag, e.g. Platform[@toolName='Microsoft Visual Studio Solution File, Format Version 12.00']

**Comment by hach-que** [comment]
Closing this as the world has changed since this was filed (in particular with where .NET is heading).

Right now Protobuild always picks the latest MSBuild tools version for the C# projects it generates, which seems to give good results.
