### ISSUE TITLE
Do ConentProjects have a way to hook into content building?

### ISSUE THREAD

**Issue by emarcotte** [hach-que/Protobuild#82]
It seems like defining a content project doesn't do very much. I'm reading https://protobuild.readthedocs.org/en/latest/content_projects.html and not understanding what they offer. Trying to add it one to a test project, it seems like protobuild just evaluates the content project things during syncing and does not generate a project file. I am hoping to find a way to run monogame's content builder tools. Does this require writing XSL to generate the build steps into a project file manually?

Hoping to replace some cobbled together perl script to run my content generation commands (I don't quite understand msbuild yet).

Thanks!
Eugene

**Comment by hach-que** [comment]
Content projects provide you with the ability to add wildcard-based content to a project (i.e. "all *.png files from this directory").  Wildcards do not work in MSBuild in a cross-platform manner, and don't behave well when adding or removing files through the IDE.

For engines like MonoGame, you'd make a content project point to the directory that contains your compiled content.

For engines like Protogame (which compile content on-the-fly), you'd make a content project point to both the source files and the compiled files for the target platform, like so (assets in this are the source files):

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentProject Name="Unearth.Content">
  <Source Include="Unearth.Content/assets" Match="*" Primary="true" />
  <Source Include="Unearth.Content/compiled" Match="*.bin" />
</ContentProject>
```

There's some discussion in the MonoGame upstream around allowing content to be compiled on-the-fly: https://github.com/mono/MonoGame/issues/3198.  This is (in my opinion) the best way forward.

In general, content compilation that is performed as part of the build (either inside MSBuild or part of Protobuild) is very difficult to get right for all engines, all applications and most importantly, get right in a cross-platform manner.  For this reason, we haven't supported anything in this area explicitly.

You can use `AdditionalProjectTransforms.xslt` to add additional MSBuild content to the generate project (and you can use XSL conditions to change behaviour based on platforms).  Inside the additional project transforms, you can use a loop like this to get a list of all of the content files:

```
<xsl:for-each select="$project/References/Reference">
  <xsl:variable name="include-path" select="./@Include" />
  <xsl:if test="count(/Input/Projects/ContentProject[@Name=$include-path]) > 0">

            <xsl:for-each select="/Input
                                  /Projects
                                  /ContentProject[@Name=$include-path]
                                  /Compiled">
                  <SomeTagThatDoesSomething>
                    <xsl:attribute name="Include">
                      <xsl:value-of
                        select="user:GetRelativePath(
                      concat(
                        /Input/Generation/RootPath,
                        $project/@Path,
                        '\',
                        $project/@Name,
                        '.',
                        /Input/Generation/Platform,
                        '.csproj'),
                      current()/FullPath)" />
                    </xsl:attribute>
                  </SomeTagThatDoesSomething>
    </xsl:for-each>
  </xsl:if>
</xsl:for-each>
```

**Comment by emarcotte** [comment]
Cool. Thanks for the link and snippets. I'll play around some!
