### ISSUE TITLE
Exclude projects from references?

### ISSUE THREAD

**Issue by emarcotte** [hach-que/Protobuild#93]
Is it possible to exclude a project from a referenced package? For example, if I make a project that references MonoGame, I get their MonoGame.Tests.{Platform}. I don't reference anything from there, so it would save a bit of excess to be able to exclude it.

**Comment by hach-que** [comment]
If a referenced package or submodule uses service dependencies, then only the projects who provide services that are depended on will be in the solution.  MonoGame uses service dependencies for the main project, but not for their tests.

Basically, something similar to the following needs to be added to the MonoGame.Tests project:

```
<Services>
  <Service Name="Default">
    <DefaultForRoot>True</DefaultForRoot>
  </Service>
</Services>
```

Once this is added, the tests project won't be included in the solution for anyone consuming the MonoGame library, but will still be included in the MonoGame solution itself.

**Comment by emarcotte** [comment]
Cool. I'll see if they're interested in such a change. Thanks again!
